#Key tasks
- name: Including Zabbix repo
  apt_repository:
    repo: "deb http://repo.zabbix.com/zabbix/{{ zabbix_version }}/ubuntu {{ ansible_distribution_release }} main"
    filename: zabbix.list
    state: present

- name: Adding Zabbix apt_key
  sudo: yes
  apt_key:
    url: "https://repo.zabbix.com/zabbix-official-repo.key"
    state: present

- name: Adding Grafana apt_key
  sudo: yes
  apt_key:
    url: "https://packages.grafana.com/gpg.key"
    state: present
    validate_certs: false
  tags:
    - grafana


- name: Including Grafana repo
  apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"
    filename: grafana.list
    state: present
  tags:
    - grafana

